on:
  issues:
    types: [opened]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    permissions:
      issue: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['requires_review']
            })